### ISSUE TITLE
StudioRack

### ISSUE THREAD

**Issue by RustoMCSpit** [brummer10/Ratatouille.lv2#10]
It's an open-source plugin manager called StudioRack:
https://github.com/studiorack

The aim of the project is to provide a free open-source way to manage plugin dependencies and their versions. It would involve the following steps:

    Publish a Github release containing the plugin source along with metadata plugins.json
    Tag your Github repository with studiorack-plugin so it can be discovered
    Wait for the studiorack-registry to index your plugin (every 24 hours)
    Check the registry feed for your plugin to appear

**Comment by brummer10** [comment]
I'm currently can't see any benefit from using StudioRack. 
Ready to use binaries been provided on the release page for Linux/windows already here. They comes with the benefit of no external dependency (using PawPaw). Looking at the workflow files from StudioRack it looks that binaries build with them are only usable on up to date distributions and comes with external dependencies to special versions of the used libraries (ubuntu-latest). 
While the idea of having a single plugin manager tool online available is nice, it seems that the build system it use didn't cover this idea in regards to Linux. It may work better for Windows and Mac, but still there dependencies needs to be covered by the user.

**Comment by RustoMCSpit** [comment]
> I'm currently can't see any benefit from using StudioRack. Ready to use binaries been provided on the release page for Linux/windows already here. They comes with the benefit of no external dependency (using PawPaw). Looking at the workflow files from StudioRack it looks that binaries build with them are only usable on up to date distributions and comes with external dependencies to special versions of the used libraries (ubuntu-latest). While the idea of having a single plugin manager tool online available is nice, it seems that the build system it use didn't cover this idea in regards to Linux. It may work better for Windows and Mac, but still there dependencies needs to be covered by the user.

any issues like this should be made as issues on the github repo, the main dev is working hard to get out of alpha and feedback like this is massively helpful.

**Comment by brummer10** [comment]
Sorry, that isn't my part in this game. If you would help to support StudioRack and make it better, you could forward my response from here. I'm myself already have more projects running I could handle. So, for example, if you wish to see support for StudioRack in Ratatouille, fork Ratatoille, add support and make a pull request. I'm not against that, just, I wouldn't spend any time to figure out how it works, test it and implement support for it, as I said, I didn't see any benefit, not for me, nor for users of Ratatouille.
