### ISSUE TITLE
would it be possible to use the below two projects to make a GUI?

### ISSUE THREAD

**Issue by RustoMCSpit** [brummer10/Ratatouille.lv2#12]
https://github.com/brummer10/Ratatouille.lv2
for ratatouille, the Neural-Amp-Modeler and the RTNeural loaders into self contained C++ classes it wont be to hard to reuse them in other projects. Same is true for the convolver class and the dcblocker.

https://github.com/Chowdhury-DSP/BYOD
for BYOD, there is a signal chain type GUI that already accepts IRs and will just need to accept NAM files

originally posted:
https://github.com/mikeoliphant/neural-amp-modeler-lv2/issues/67

**Comment by brummer10** [comment]
Feel free to use those classes and do so. But note, RTNeural is, as well as BYOD, original written by [jatinchowdhury18](https://github.com/jatinchowdhury18), so, implementing a model loader into BYOD as plugin would be straight forward for him.

**Comment by RustoMCSpit** [comment]
> Feel free to use those classes and do so. But note, RTNeural is, as well as BYOD, original written by [jatinchowdhury18](https://github.com/jatinchowdhury18), so, implementing a model loader into BYOD as plugin would be straight forward for him.

okay ive contacted them about it, thanks!
