### ISSUE TITLE
Unload profile

### ISSUE THREAD

**Issue by Boone777** [brummer10/Ratatouille.lv2#13]
Is there  a way to unload a profile ?
For exemple I set a pedal but it turns out after checking a few higain amp profiles that the pedal is to much gain for certain models. For now I have to start from scratch with a new instance because I can't unload/turn off the pedal.

Also as a suggestion, arrows for next/previous profile or mouse over scroll will be a very much welcome for scrolling through a bunch of profiles.

**Comment by brummer10** [comment]
The little button on the left side of the filename does that, the one with the arrow down. It popup a menu with all usable models from the same directory and the last entry is "None". Select that to unload a model.

**Comment by Boone777** [comment]
🤦‍♂️ I need a bigger facepalm... but on my MXLinux to my defense, the scroll is not easy to spot, in fact the entire interface makes me squint like the character could benefit from being much bolder. It did not help that I had only 1 profile in that specific folder, you would expect the none option to show right away without scrolling. Probably a Linux thing it's nothing new really.

**Comment by brummer10** [comment]
You could resize the GUI, that will as well resize the character. Scrolling works best with the mouse-wheel, you could scroll by just use the mouse-wheel on the menu. No need to use the scrollbar.
