### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by Zodi-ark** [brummer10/Ratatouille.lv2#15]
Is there a guide somewhere on how to install this. Im on windows and use Reaper if that matters. I'm not really a techy person I just play the guitar :(

**Comment by brummer10** [comment]
When you've download 
https://github.com/brummer10/Ratatouille.lv2/releases/download/v0.4/Ratatouille.lv2-v0.4-win64.zip 
unpack it and copy it to 
/Program Files/Common Files/LV2
in case you didn't have a LV2 directory under /Program Files/Common Files/, create it before.
Reaper should find it then on the next start (maybe you must rescan the plugs)

**Comment by Zodi-ark** [comment]
Thanks for the help but I got a new problem. The NAM Model A and B slots are working but the IR slots wont take anything. It pops up for a quarter of a second and goes back to none.

**Comment by brummer10** [comment]
Mmm, I need to fire up my windows box to check what's going on. I just did a quick check using wine under linux and that works as expected. Give me some day's, I'll check and come back.

In the mean time, maybe you could check if this one works for you:
https://github.com/brummer10/ImpulseLoader.lv2/releases/download/v0.2/ImpulseLoader.lv2-v0.2-win64.zip

it is the plain IR loader, it use the same technic then the ones in Ratatouille. Would be helpful to know if this one works for you.

**Comment by Zodi-ark** [comment]
Just tried it. Yup it doesn't work. Also I noticed that when I browse for all supported files without the UI it only lists .audio whereas Ratatouille lists .audio and .wav. All of my IRs are wav files.

**Comment by brummer10** [comment]
So now I'm puzzled. I've just tried it (windows10) with Reaper and it all works as expected. No problem loading IR files here.

**Comment by Zodi-ark** [comment]
Next day, restarted my pc now its working. Thank you so much!
