### ISSUE TITLE
IR Loader Won't Work (Windows 11 - Reaper)

### ISSUE THREAD

**Issue by Zodi-ark** [brummer10/Ratatouille.lv2#16]
Can only add IRs when fx chain is disabled. Enabling the fx chain removes the IRs. In the video even when there is only 1 IR after initially turning on the fx chain its defiantly not there.

https://github.com/brummer10/Ratatouille.lv2/assets/113886368/58ea01ce-6ab2-4f72-9bb7-d080cb526066

**Comment by brummer10** [comment]
Do you've the same issue when using the Ratatouille GUI?
Which version of Reaper is it? I just tested it again here on windows, and it just works. 
Could you maybe start reaper from a terminal, then there should be some output there when the IR File loading fail.

**Comment by Zodi-ark** [comment]
Same issue using the GUI. Using the latest Reaper version 7.17. Started reaper from a terminal but it didn't show anything. 
![Screenshot 2024-07-05 021950](https://github.com/brummer10/Ratatouille.lv2/assets/113886368/40211299-2644-4d2d-a03b-bbe82d197051)

**Comment by brummer10** [comment]
I've currently no idea how to solve that. As I said, here on windows10 it works flawless. I may going to update to wondows11 within the next day's to see if that makes a different, but can't promise any thing.

**Comment by brummer10** [comment]
Okay, I see now what the issue is. 
You're  buffer-size 192. The convolution engine didn't like that. Try please with 128 or 256.
In the mean time I'll investigate to make it work with any buffer-size.

**Comment by brummer10** [comment]
I've pushed a new release aims to fix this issue. 
https://github.com/brummer10/Ratatouille.lv2/releases/download/v0.5/Ratatouille.lv2-v0.5-win64.zip

let me know please if it works for you now as well.

**Comment by Zodi-ark** [comment]
Yup its working.
