### ISSUE TITLE
Loading IR seems to create DC issues.

### ISSUE THREAD

**Issue by 38github** [brummer10/Ratatouille.lv2#17]
I compiled the up to date code and it loads NAM files correctly. However when I add IR in the third slot (haven't tried the fourth) my channel in REAPER auto mutes and when I try to unmute it I hear the low frequency thump that I associate with DC issues. I have tried several IRs but they all do this. When I choose "None" in that slot the issue goes away.

I have compiled it with Clang 18 and _x86_64-v3 -O3 -flto -fopenmp -openacc_.

**Comment by brummer10** [comment]
Strange, I never experience that. 
Is that just with the latest checkout or do you get the same with the last release?
One thing, when you've done a git pull on a older checkout, run `make clean` before do a new build.
Why did you add those flags? There are some checks in the makefile to setup best matching flags for build, please try a simple `make`
during the build output there is a Info part, that one I'd like to see, here it is
```
 INFO: optimised for -march=x86-64-v3 -msse3 -mfpmath=sse -mfxsr
 INFO: build with    clang++    
 INFO: using         -std=c++20
```
by default, Ratatouille is build with ` -Ofast`, not with ` -O3 `

**Comment by brummer10** [comment]
Did just a quick test in Reaper, I can't reproduce the issue here.
![Peek 2024-08-03 13-25](https://github.com/user-attachments/assets/dc21a5b1-ae39-4add-a58f-368181abdbb7)

**Comment by 38github** [comment]
> Why did you add those flags?

https://eigen.tuxfamily.org/dox/TopicMultiThreading.html

> Is that just with the latest checkout or do you get the same with the last release?

It was a clean git clone. With the 0.7 release tar ball I can't load an impulse response. When I have opened the file it does not display in the plugin.

> please try a simple make

```
 =================== DONE =======================
 INFO: optimised for -march=x86-64-v3 -msse3 -mfpmath=sse -mfxsr
 INFO: build with    clang++    
 INFO: using         -std=c++20
```
Same thing happened with the new build without any added flags.

**Comment by 38github** [comment]
The volume is ramping up after a second and causes the channel to auto mute.

**Comment by brummer10** [comment]
Could you give me some more info,
Your Session Sample Rate:
your buffer size settings:
Sample Rate of the IR File:
size of the Ir File (samples or ms):
is it a stereo IR File:
Do you enabled oversampling in Reaper:
happen the issue with any other host, ardour, carla, qtractor, . . .  :

**Comment by brummer10** [comment]
Still I can't reproduce the issue, but, I tempted to push a fix for it. Please let me know if the last commit fix the issue for you.

**Comment by 38github** [comment]
> Still I can't reproduce the issue, but, I tempted to push a fix for it. Please let me know if the last commit fix the issue for you.

Hey! That seems to have fixed it! Thank you!
