### ISSUE TITLE
Eigen issues: (1) it fails to find Eigen headers (2) 

### ISSUE THREAD

**Issue by yurivict** [brummer10/Ratatouille.lv2#19]
(1)
This error:
```
In file included from ../NeuralAmpModelerCore/NAM/activations.cpp:1:
../NeuralAmpModelerCore/NAM/activations.h:6:10: fatal error: 'Eigen/Dense' file not found
    6 | #include <Eigen/Dense>
      |          ^~~~~~~~~~~~~
1 error generated.
```
is because CXXFLAGS is missing ```pkg-config --cflags eigen3```.

(2)
Build fails with this error:
```
n file included from ../NeuralAmpModelerCore/NAM/get_dsp.cpp:8:
../NeuralAmpModelerCore/NAM/lstm.h:26:84: error: no member named 'lastN' in namespace 'Eigen::placeholders'
   26 |   Eigen::VectorXf get_hidden_state() const { return this->_xh(Eigen::placeholders::lastN(this->_get_hidden_size())); };
      |                                                               ~~~~~~~~~~~~~~~~~~~~~^
```

Not sure why lastN isn't found.

**Comment by brummer10** [comment]
Eigen is already included in the NAM sources as submodule and NAM needs to be build against  this special revision of eigen. Building against a newer revision fails. 
If Eigen/Dense not found there must be something wrong with the include path. Could you show me what you get with 
`make V=1`  --> turns on verbose mode to see the command for the compiler.

should be like this
`clang++     -march=x86-64-v3 -std=c++20 -MMD -flto=auto -fPIC -DPIC -Ofast -Wall -funroll-loops -msse3 -mfpmath=sse -mfxsr -Wno-sign-compare -Wno-reorder -Wno-infinite-recursion -DUSE_ATOM -DFFTCONVOLVER_USE_SSE=1 -fomit-frame-pointer -fstack-protector -fvisibility=hidden -fdata-sections -I. -I./ -I./zita-resampler-1.1.0 -I../FFTConvolver/ -I../delegate/include/delegate/ -DRTNEURAL_DEFAULT_ALIGNMENT=32 -DRTNEURAL_USE_EIGEN=1 -DRTNEURAL_NAMESPACE=RTNeural -DDSP_SAMPLE_FLOAT -DNAM_SAMPLE_FLOAT -Dneural_amp_modeler_EXPORTS -Wno-unused-private-field -fdenormal-fp-math=positive-zero -MMD -Wall -c ../NeuralAmpModelerCore/NAM/activations.cpp -o ../NeuralAmpModelerCore/NAM/activations.o  -I../NeuralAmpModelerCore/NAM/ -I../NeuralAmpModelerCore/Dependencies/eigen/ -I./ -I../NeuralAmpModelerCore/Dependencies/nlohmann/`

**Comment by yurivict** [comment]
The eigen submodule was missing.

Now the error is:
```
 Building object file RtNeuralModel.o 
c++ -O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -std=c++20 -MMD -flto=auto -fPIC -DPIC -Ofast -Wall -funroll-loops  -Wno-sign-compare -Wno-reorder -Wno-infinite-recursion -DUSE_ATOM  -fomit-frame-pointer -fstack-protector -fvisibility=hidden -fdata-sections -I. -I./ -I./zita-resampler-1.1.0 -I../FFTConvolver/ -I../delegate/include/delegate/ -DRTNEURAL_DEFAULT_ALIGNMENT=32 -DRTNEURAL_USE_EIGEN=1 -DRTNEURAL_NAMESPACE=RTNeural -DDSP_SAMPLE_FLOAT -DNAM_SAMPLE_FLOAT -Dneural_amp_modeler_EXPORTS -Wno-unused-private-field -fdenormal-fp-math=positive-zero -MMD  -c RtNeuralModel.cpp -o RtNeuralModel.o -I../NeuralAmpModelerCore/NAM/ -I../NeuralAmpModelerCore/Dependencies/eigen/ -I./ -I../NeuralAmpModelerCore/Dependencies/nlohmann/ -I../RTNeural/RTNeural/ -I../RTNeural/modules/Eigen/ -I./ -I../RTNeural/modules/json/ 
In file included from RtNeuralModel.cpp:10:
./ModelerSelector.h:20:10: fatal error: 'dsp.h' file not found
   20 | #include "dsp.h"
      |          ^~~~~~~
1 error generated.
```

**Comment by brummer10** [comment]
wired, that's the NAM core header located in ` ../NeuralAmpModelerCore/NAM/`
maybe, you could try to add the include path in Ratatouille/makefile line 262 before the source file, I usually put the behind the object file.
change
`$(QUIET)$(CXX) $(CXXFLAGS) -MMD  -c $(patsubst %.o,%.cpp,$@) -o $@ $(NAM_INCLUDES) $(RTN_INCLUDES)`
to
`$(QUIET)$(CXX) $(CXXFLAGS) -MMD $(NAM_INCLUDES) $(RTN_INCLUDES) -c $(patsubst %.o,%.cpp,$@) -o $@ `

but, I guess that wouldn't help as for building the nam and rtneural object files the same syntax was used and worked.

**Comment by brummer10** [comment]
Hi @yurivict 
So I've installed FreeBSD in a virtual box and checked what happens. 
At least I guess I've no fixed all remaining issues for build on FreeBSD.
Note, for using Neural Models in realtime context it is important to have some SIMD optimisations enabled. 
Ratatouille use sse instructions and x86-64-v3 optimisations.  The makefile detect if the build machine support those. 
That works now as well on FreeBSD. 
Let me know if you still having issues to build Ratatouille
