### ISSUE TITLE
Permission to publish Ratatouille on Flathub?

### ISSUE THREAD

**Issue by runiq** [brummer10/Ratatouille.lv2#24]
Hey,

as per the [Flathub submission guidelines](https://docs.flathub.org/docs/for-app-authors/submission/#theres-an-app-that-id-like-to-see-on-flathub-but-im-not-the-developer), I would like to ask you for permission to publish this plugin on Flathub. I will gladly give you access to the repo in case you want to submit updates yourself; otherwise I'll do my best to keep the package up to date.

**Comment by brummer10** [comment]
Hi
Sure. You've all permissions you need already by the chosen License. But thanks a lot for asking. I would prefer if you keep the maintenance for Flathub. Thanks for your work on this. 
regards
hermann
