### ISSUE TITLE
Error when compiling for AArch64: unknown architecture `armv8'

### ISSUE THREAD

**Issue by runiq** [brummer10/Ratatouille.lv2#25]
See https://github.com/flathub/flathub/pull/5547#issuecomment-2321973584 -- when trying to build for Flatpak, the architecture `armv8` is not recognized:

```
=================== DONE =======================
make[1]: warning: -j1 forced in submake: resetting jobserver mode.
 INFO: optimised for -march=armv8 
 INFO: build with    aarch64-unknown-linux-gnu-g++
 INFO: using         -std=c++20
Building object file ../NeuralAmpModelerCore/NAM/activations.o 
cc1plus: error: unknown value ‘armv8’ for ‘-march’
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a armv9.1-a armv9.2-a armv9.3-a native; did you mean ‘armv8-a’?
Assembler messages:
Error: unknown architecture `armv8'
Error: unrecognized option -march=armv8
make[1]: *** [makefile:245: ../NeuralAmpModelerCore/NAM/activations.o] Error 1
make: *** [makefile:36: Ratatouille] Error 2
FB: host_command_exited_cb 3428615 512
```

It looks like you need to set a [specific profile](https://stackoverflow.com/a/56444033/1145828), for example [armv8-a](https://developer.arm.com/Architectures/A-Profile%20Architecture) or [armv8-r](https://developer.arm.com/Architectures/R-Profile%20Architecture).

> The Arm Application-profile (A-profile) architecture targets high performance markets, such as PC, mobile, gaming, and enterprise.

> The R-profile provides high-performing processors for timing sensitive and safety-critical environments.

Out of curiosity, which compiler did you use that accepted the generic `armv8`?

**Comment by brummer10** [comment]
I must admit that I didn't take much care for arm architecture.  
It's more than 10 years ago I wrote this makefile part and I just reuse it all the time. 
Usually when I build for arm (mostly for MOD) I set my own flags by overwrite the SSE_CFLAGS macro with the needed flags, so I never noticed that armv8 isn't valid any more.
I'll push a commit and set it to armv8-a

**Comment by brummer10** [comment]
done

**Comment by runiq** [comment]
That worked. Thanks a lot! :)
