### ISSUE TITLE
CPU optimization flag detection does not work on aarch64

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/Ratatouille.lv2#26]
See our CI build log from a Raspberry Pi CI build runner here:

https://ci.cbix.de/osam-cologne/archlinux-proaudio/2044/2/3

```
[...]
Build static library libxputty.a 
 =================== DONE =======================
make[1]: warning: -j1 forced in submake: resetting jobserver mode.
 INFO: optimised for -msse3 -mfpmath=sse -mfxsr -march=x86-64
 INFO: build with    g++
 INFO: using         -std=c++20
 Building object file ../NeuralAmpModelerCore/NAM/activations.o 
g++: error: unrecognized command-line option ‘-msse3’
g++: error: unrecognized command-line option ‘-mfpmath=sse’
g++: error: unrecognized command-line option ‘-mfxsr’
make[1]: *** [makefile:261: ../NeuralAmpModelerCore/NAM/activations.o] Error 1
make: *** [makefile:36: Ratatouille] Error 2
```

**Comment by brummer10** [comment]
Is this cross compile?
If so, you must use the SSE_CFLAGS target to build like this
`make SSE_CFLAGS=""`

**Comment by SpotlightKid** [comment]
No, it is a Raspberry Pi with a 64-bit distro building for aarch64.

I suspect that one of the commands in the Makefile to detect the architecture is a failing. E.g. I'm not sure the `arch` command exists on every system.

**Comment by brummer10** [comment]
Still strange, as the makefile checks for the CPU flags given by `cat /proc/cpuinfo `
However, using the SSE_CFLAGS target avoid any automatic applied optimisation and allow you to implement your own flags.

**Comment by brummer10** [comment]
I see it still fail to build on aarch64. 
After recheck I noticed that there I've implemented a additional flag for FFT_Convolver sse optimisation, it's 
FFT_FLAG. So to disable that you should use
`make SSE_CFLAGS="" FFT_FLAG=""`

Seems I need to rework this logic to avoid such hassle. 
But mostly I wonder why cat /proc/cpuinfo providing cpu flags which indicate sse support.

**Comment by SpotlightKid** [comment]
Ok, unsetting both SSE_CFLAGS and FFT_FLAG works.

BTW, I think the aarch64 builder runs in a docker container on a Raspi. Not 100% sure, because @cbix, who runs the server, is currently on holiday. But that apparently changes the output of `/proc/cpuinfo` and makes several other diagnostic tools unavailable.

You can see [here](https://ci.cbix.de/osam-cologne/archlinux-proaudio/2051/2/3) starting on line 588 where I tried to output some information on the exact Raspi model used, but most of it didn't work. But there is the CPU info at least.

**Comment by cbix** [comment]
> BTW, I think the aarch64 builder runs in a docker container on a Raspi.

Not on a RasPi but on an Ampere arm64 VM at Hetzner :)

**Comment by brummer10** [comment]
I'm currently trying to implement support for Host versus Target flags from the CPU, maybe that could solve this issue. I may come up with a reworked makefile within the next day's, would be cool if you could try it then.

**Comment by runiq** [comment]
> Is this cross compile? If so, you must use the SSE_CFLAGS target to build like this
>
> ```
> make SSE_CFLAGS=""
> ```

Just for the record: Unsetting that will compile x86_64 without optimizations, so I need different `make` invocations for x86_64 and aarch64, right?

**Comment by brummer10** [comment]
> Just for the record: Unsetting that will compile x86_64 without optimizations, so I need different `make` invocations for x86_64 and aarch64, right?

When you compile on a x86_64 machine, yes. Otherwise, when using a virtual machine, or a cross tool chain it will compile binaries compatible with the Target flag of the used compiler and not optimize them for the used CPU. 
You could set the compiler to use, for example like this
`make CXX="arm-none-eabi-g++" SSE_CFLAGS="" FFT_FLAG=""`

you could set the needed optimisation flags in the SSE_CFLAGS field as well.

**Comment by brummer10** [comment]
I've pushed now a update to the makefile to take -dumpmachine from the compiler into account. That should avoid this issue and should allow to build for different arch by just make. True, that will miss then any optimisation at all. 
I'm open to implement optimisation flags for special arch, but I didn't know which ones will be useful. That will be welcome by pull requests.
Anyhow, at first it would be interesting for me if your workflows fly with the latest changes in the makefile.

**Comment by SpotlightKid** [comment]
> Anyhow, at first it would be interesting for me if your workflows fly with the latest changes in the makefile.

Sorry, our packages are currently not set up to build from Git HEAD, and I don't really have the time to change the package to compile from Git, just for testing, since that would require setting up the Git sub-modules as well, which is a bit more involved for proper AUR packages.

Could you maybe point me to a commit (or two or three), which I could use as patches against the release version sources?

**Comment by brummer10** [comment]
Latest release (0.9.1) should fix this issue. btw. there is now a arm64 binary build available.
https://github.com/brummer10/Ratatouille.lv2/releases/tag/v0.9.1

**Comment by SpotlightKid** [comment]
Confirmed fixed. We were able to remove the special handling of aarch64 from our build.
