### ISSUE TITLE
Regression: File-Dialog and Plugin do not follow sy.bolic links in path

### ISSUE THREAD

**Issue by DevFreeTwo** [brummer10/Ratatouille.lv2#27]
The symlinks used to work in version 0.3.

In 0.9.1 symbolic-links to directories in the path of NAM or IR files are not accessible.
The file-dialog does not show them as folders. And in Ardour Plugin-settings referring to paths with symlinks lead to not loading anything at all.

_Originally posted by @DevFreeTwo in https://github.com/brummer10/Ratatouille.lv2/issues/20#issuecomment-2376103265_

**Comment by brummer10** [comment]
Should be fixed within the latest commit. 
Indeed it was introduced when I implement support for FreeBSD in libxputty.

**Comment by DevFreeTwo** [comment]
Works again. Issue can be closed.
