### ISSUE TITLE
Building on Ubuntu 24.04 LTS Failed with clang

### ISSUE THREAD

**Issue by Schmitty2005** [brummer10/Ratatouille.lv2#28]
when using 'make', this will not build with clang on my system. (Ubuntu 24.04 LTS )  I get an error of : 
```

INFO: optimised for -msse3 -mfpmath=sse -mfxsr -DUSE_SSE -march=x86-64-v3
 INFO: build with    clang++    
 INFO: using         -std=c++20
 Building object file ../NeuralAmpModelerCore/NAM/activations.o 
In file included from ../NeuralAmpModelerCore/NAM/activations.cpp:1:
../NeuralAmpModelerCore/NAM/activations.h:3:10: fatal error: 'string' file not found
    3 | #include <string>
      |          ^~~~~~~~
1 error generated.
make[1]: *** [makefile:283: ../NeuralAmpModelerCore/NAM/activations.o] Error 1
make: *** [makefile:36: Ratatouille] Error 2
```

I manually changed Ratatouille makefile line # 21 to g++ instead of clang:
`CXX := g++`

and the build worked just fine. I used Ratatouille.lv2 in Ardour  for about 1.5 hours with no issue.

Is there something wrong with my clang++ build system ?   Or is this a Ratatouille.lv2 bug ? 

This is a great plug-in.  Thank you!

**Comment by brummer10** [comment]
I'm glad to hear you like it. 
For build with clang you may need to install `libstdc++{Your Clang Version}-dev`
