### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by avanzzzi** [brummer10/Ratatouille.lv2#30]
This plugin is awesome but I'm missing the normalization feature available in NAM plugin, which normalizes only the NAM block even when not using the IR block.

Also, the actual normalization Ratatouille has does something weird: When I load a very quiet IR (~ -16 dB peak), it sounds ultra loud when Normalization is active.

IR file stats:
![image](https://github.com/user-attachments/assets/abfe1a55-7ed9-42d0-a933-8f5bf7aeb6bf)

IR loaded on NadIR (normalized):
![image](https://github.com/user-attachments/assets/79651d55-27eb-4594-9f75-f47affebfdde)

IR loaded on Ratatouille:
![image](https://github.com/user-attachments/assets/d81fe477-9bf8-4a2c-b040-f0ed537bc356)

IR loaded on Ratatouille (normalized):
![image](https://github.com/user-attachments/assets/7f4bb3d9-f965-44ce-a5a7-4abd4b4d92e6)

Thank you for your awesome work!

**Comment by brummer10** [comment]
Glad to hear it is useful. I've implemented normalization for NAM models now. Note that it only works with models providing the loudness factor. 

To the normalization of the IR files, it is done to adjust the loudness of IR files to the same level. So, when you switch a IR file it shouldn't have any influence on the output level. 
It is clear that a quit IR file become louder while a loud IR file become more quieter. 

I must admit that the curves you presented didn't look right. Still, I like to ask when you switch IR files, do you get a different output level?

**Comment by avanzzzi** [comment]
> Glad to hear it is useful. I've implemented normalization for NAM models now. Note that it only works with models providing the loudness factor.

Awesome, thank you very much. Given the amount of different normalizations available, just to  be clear, in my first point I was talking about output normalization, which can be set here, in NAM:
![image](https://github.com/user-attachments/assets/962b39b0-947d-41b8-9e03-0caf22d78497)

I understand that Ratatouille uses RAW mode, which is great already. So, in my first point I was talking about the "Normalized" option, available for all models even when there's no metadata (that used to be a switch in the UI, now it's in the settings). It's really useful as it makes up for different output capture setups.

> It is clear that a quit IR file become louder while a loud IR file become more quieter.

Agreed

> I must admit that the curves you presented didn't look right. Still, I like to ask when you switch IR files, do you get a different output level?

Yeah, very different.

Ratatouille first increases it to a higher level, then, with a normalized file (0 dB peak IR), normalization will bring it back to an "around zero" value:

![image](https://github.com/user-attachments/assets/f3f6eb72-a086-416e-a3f5-73d3e6638b83)

![image](https://github.com/user-attachments/assets/79156a6a-6fc6-45b1-bd6b-84b9f37a1a4a)

Maybe it doesn't need to be increased first?

That quieter IR file.

![image](https://github.com/user-attachments/assets/015325a3-295f-4fa0-a172-f71593edba27)

![image](https://github.com/user-attachments/assets/80d2cdf2-6fa1-4c6e-a170-e22a6048d835)

With this file, that first increase already puts it "around zero" then when I set the normalization, it adds to makes it really loud.

Thanks!

**Comment by brummer10** [comment]
> Agreed
> 
> > I must admit that the curves you presented didn't look right. Still, I like to ask when you switch IR files, do you get a different output level?
> 
> Yeah, very different.

I mean when you've normalisation active. 

> Ratatouille first increases it to a higher level, then, with a normalized file (0 dB peak IR), normalization will bring it back to an "around zero" value:

No, Ratatouille doesn't do such. It just load the IR file as it is (using libsndfile) into a buffer. When normalize is selected, it calculate the square root of the complete file and calculate a gain factor to bring that (the square root) to zero, so that when it is used in convolution it have no influence on the loudness. 
Hence I wonder that you get different loudness  levels when normalisation is on and you switch a IR file.

**Comment by brummer10** [comment]
To the NAM normalisation, if you mean this one:
https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/main/NeuralAmpModeler/NeuralAmpModeler.cpp#L655

That's what I've implemented with the latest commit, the normalisation for case 1: //normalize
As far I could see it only works in there as well only when the model provide the needed meta data.

**Comment by avanzzzi** [comment]
Interesting. Maybe something with libsndfile as tThe same happens in ImpulseLoader. After convolution using Ratatouille or ImpulseLoader, a sample with peak 0 dB and an IR with peak 0 dB will be at around +20 dB.


> As far I could see it only works in there as well only when the model provide the needed meta data.

Yeah, that's the one. You are right, the model must provide it. Much appreciated!

Recently, the calibrated method for input and output was implemented, which is why I was confused. But you are right, in the earlier versions the models didn't even have the normalized method.

**Comment by brummer10** [comment]
I don't think that there could be something wrong with libsndfile (given how wide it is used). I'll take the stab and rethink my normalisation function (there are so many way's to do it) as that should be more expected to be the culprit. 
I mean, it works for me in all cases I've tested, but it seems you found some corner cases were it fail badly. I need to find out why.

**Comment by avanzzzi** [comment]
I'm sending the IR file, maybe that could help. Meanwhile I'll take a look at the code to see if I find something. Thanks!
[SM57_2.zip](https://github.com/user-attachments/files/18152300/SM57_2.zip)

Just compiled the code, I'll check the model normalization, thanks again!
Edit.: It's working, awesome!

**Comment by brummer10** [comment]
Thanks, that will help. 
The code I use for normalisation of the IR files is here:
https://github.com/brummer10/Ratatouille.lv2/blob/main/Ratatouille/fftconvolver.cc#L297

**Comment by avanzzzi** [comment]
Maybe when factor is less than 1, you get unexpected results.

I'm problably wrong, but to normalize, wouldn't it be necessary to divide the absolute value of each sample by the maximum peak value?

Something like that (pseudo code):
```
for each sample n:
     magnitude(sample n) = abs(sample n)
     normalized(sample n) = magnitude(sample n) / maximum_magnitune
```

**Comment by brummer10** [comment]
Okay, the IR file helps. 
My intention was to get the square root of the IR file to zero so that only the eq curve get applied. But my attempt only work's when the file level is above 1. 
I've switched now to a simple normalisation formula to make it even work for all files. Downside is that we can't negate the loudness influence this way, but we could make it even, that's good as well I think.
Thanks for pointing out this issue, let me know if it works for you now the way you expected.

**Comment by avanzzzi** [comment]
It works for all files now, thanks.

I think the loudness can be a problem because it's very loud now and you can't control it with the output knob. Since I have already caused you a lot of trouble, I'll try something and send a pull request later.

**Comment by brummer10** [comment]
It may be a good Idea to reimplement my older loudness compensation algorithm just after the normalisation. So the normalisation ensure that the square root is above 1 and the loudness compensation works then for all files, as well when they comes with less loudness like your example file.

**Comment by brummer10** [comment]
I've done some tests and it seems to work flawless now. So I pushed it to the repository.

**Comment by avanzzzi** [comment]
I see you already fixed, not sure if it will get merged but here it is: https://github.com/brummer10/Ratatouille.lv2/pull/32

**Comment by brummer10** [comment]
I've commented on the pull request. I see some issues with this optimisation so I can't merge it. 
I guess what we could do is fetching the square root value in the same loop were we apply the normalisation factor, that will spare one loop.

**Comment by avanzzzi** [comment]
I've changed the pull request so it sums the squared values of normalized buffer, like you said.

**Comment by brummer10** [comment]
Nice. Thanks for your contribution, it's merged now.
