### ISSUE TITLE
Only lists .nammodels and not .nam 

### ISSUE THREAD

**Issue by 38github** [brummer10/Ratatouille.lv2#4]
Only lists .nammodels and not .nam

**Comment by brummer10** [comment]
That's strange. 
Here it list all my *.nam files without issue. I didn't know that there are files out there with *.nammodel extension. Were do you get them?

**Comment by brummer10** [comment]
Ah, now I know what you talk about, You mean the internal UI from Reaper. I didn't know that Reaper supports the mod file extension. I've fixed that now so that the internal Reaper UI shows nam files in the browser.

**Comment by 38github** [comment]
Great! I will try it out!

**Comment by 38github** [comment]
Itnow works with NAM files but IR file function lists *.audio and not .wav or actual audio files.

**Comment by brummer10** [comment]
Ups, yes. Thanks for the hint. It's fixed now as well.
