### ISSUE TITLE
_ui.so crash DAW

### ISSUE THREAD

**Issue by 38github** [brummer10/Ratatouille.lv2#5]
I had to remove the _ui.so file and use the GUI-less version to avoid crashes. The terminal only says segfault error when it crashes. This might be because of some dependency issue that make didn't mention while compiling.

**Comment by brummer10** [comment]
Never see the UI crash here. Did it crash on start, or on file load, or just random?
You could build a UI less version with the command
`make mod`
that remove the reverence to the UI in the ttl file as well.

**Comment by 38github** [comment]
It crashes immediately. If I remove the second .so file which has _ui_ in its name I can then open the GUI less version.

**Comment by 38github** [comment]
I will close this as I haven't had this issue in a while. Thank you for fixing it!
