### ISSUE TITLE
CPU usage is very high

### ISSUE THREAD

**Issue by 38github** [brummer10/Ratatouille.lv2#6]
Loading just one NAM model (192kHz) uses 20% CPU compared to neural-amp-modeler-lv2 (with REAPER's oversampling) that uses 6%.

**Comment by brummer10** [comment]
DSP load depends on several factors. So, first one is optimisation. Do you use a prebuild binary? If so, do you use the one with the  x86-64-v3 optimisation?
Then, when you load a model with 192kHz expected Sample Rate, Ratatouille up-sample to that frequency. Depending on your used Session Sample Rate that may mean upsampling by the factor 4 or more. Surly that will increase the DSP load.
Here, when using 2 models with 48kHz and a Session Sample Rate of 48kHz with a 128 Frame Buffer, I've a DSP load around 12- 14%, depending on the model I load.

**Comment by 38github** [comment]
Thank you for replying.
If I load the same nam model in neural-amp-modeler-lv2 and use Reapers internal over-/upsampling to 192kHz then it only uses 6%. Your plugin, without using upsampling but instead its own internal uses 20%. I have compiled it using export flags like export `CXXFLAGS="-Ofast -flto -march=native"` but maybe make doesn't follow those.

**Comment by brummer10** [comment]
You should just use make, the optimisation flags been implemented already. 
It use -0fast and -flto=auto by default.
Check if you get a line like this:
`INFO: optimised for -march=x86-64-v3 -msse3 -mfpmath=sse -mfxsr`

**Comment by brummer10** [comment]
This is what I get here:
![2024-04-24_10-19](https://github.com/brummer10/Ratatouille.lv2/assets/2683982/0fcd96ee-0b7c-4101-920a-5aa5f6ffa348)

**Comment by 38github** [comment]
I downloaded _Ratatouille.lv2-v3-v0.1-linux-x86_64.tar.xz_ and that one works however there are a few major glitches in the UI (at least under GNOME 46 Wayland).

I loaded and loaded a nam file and got irritated that it hadn't loaded it yet but when I clicked on the downward arrow to the right of the first slot the nam filename suddenly appeared and it was obvious that it was loaded. Overall it seems it doesn't really like Wayland it seems. I will try later in an X11 session.

**Comment by brummer10** [comment]
Yes, it's a X11 GUI.

**Comment by 38github** [comment]
https://github.com/brummer10/Ratatouille.lv2/assets/18294149/a3d0fb32-df85-428c-b596-371a74a54f3b

**Comment by brummer10** [comment]
I don't know what Reaper does internal when doing oversampling, but it seems that oversampling a FX in Reaper didn't increase the DSP load, that's strange.

**Comment by 38github** [comment]
> I don't know what Reaper does internal when doing oversampling, but it seems that oversampling a FX in Reaper didn't increase the DSP load, that's strange.

No, it does increase. Without it the usage is around 0.25%.

**Comment by 38github** [comment]
I have now also tested Standard WaveNet (48 kHz) files and the CPU usage is massive. I am talking 10x than normal. I will continue using neural-amp-modeler-lv2 even though it has no internal resampler but you can always tag me if you want me to continue testing your work. Regards.

**Comment by brummer10** [comment]
Sure.
I don't know what's going on, here, I got the very same DSP load with neural-amp-modeler.lv2 then with Ratatouille. They both using the same core and nearly the same optimisation flags, so there is nothing I could improve.
Regards, and thanks for testing and feedback.

**Comment by 38github** [comment]
I tried the Windows compile (0.2) and from a quick test it seems that Ratatouille uses about the same as official Neural Amp Modeler VST3. This makes me want to try again in Linux to see why the CPU usage was so high.

**Comment by brummer10** [comment]
On Linux you get best performance when you build it from source, then the makefile could check your CPU and optimise the build flags. That's not possible with the provided binary.

**Comment by 38github** [comment]
Well, I had compiled it myself before also but this time it had better CPU usage compared to the build a couple of weeks ago.

**Comment by brummer10** [comment]
I've now implemented parallel processing for the model loaders, that reduce the dsp load for the second loaded model to ~0%
Means, you could load two models while the dsp load is just as high as if you load just one model.
