### ISSUE TITLE
.clap plugin

### ISSUE THREAD

**Issue by RustoMCSpit** [brummer10/Ratatouille.lv2#7]
hey! is it possible to make this a .clap plugin too?

**Comment by brummer10** [comment]
That's not planed, sorry.

**Comment by RustoMCSpit** [comment]
what framework is this built off of?

**Comment by brummer10** [comment]
Basically it's XUiDesigner https://github.com/brummer10/XUiDesigner so plain LV2.
but heavily modified to suit the needs. 
However, as I've put the Neural-Amp-Modeler and the RTNeural loaders into self contained C++ classes it wont be to hard to reuse them in other projects. Same is true for the convolver class and the dcblocker.

**Comment by RustoMCSpit** [comment]
what is RTNeural? 

> contained C++ classes

 so does rhat mean i can easily make a clap with them?

**Comment by brummer10** [comment]
RtNeural is a other Neural Network Modeler engine: https://github.com/jatinchowdhury18/RTNeural
You can download models for it here for example: https://cloud.aida-x.cc/all
It is not so wide spread then NAM as it is newer, but it is really good as well, and extreme lightweight in CPU consumption.   

> so does rhat mean i can easily make a clap with them?

when you are a developer and know how to write/read C++, yes.
