### ISSUE TITLE
i only get the neural part of the pligin, i dont get any IR slots?

### ISSUE THREAD

**Issue by billyblackburn** [brummer10/Ratatouille.lv2#8]
![Screenshot from 2024-04-30 22-09-26](https://github.com/brummer10/Ratatouille.lv2/assets/7400122/20eb3709-047b-475c-9fcf-ad0d7b9416ba)

**Comment by brummer10** [comment]
This looks like v0.1

**Comment by billyblackburn** [comment]
but it not tho

**Comment by brummer10** [comment]
I even checked the binary from the release and it comes as expected:
https://github.com/brummer10/Ratatouille.lv2/releases/download/v0.2/Ratatouille.lv2-v3-v0.2-linux-x86_64.tar.xz

Just it takes a bit more CPU compared to a local build.

**Comment by billyblackburn** [comment]
Ur right I had a folder called /.lv2.   is it recommended to have 2 lv2
folders?

**Comment by brummer10** [comment]
Yes. usr/lib/lv2 is for Plugins comming from your distribution, .lv2 is for presets and for Plugins comming from elswere.

**Comment by billyblackburn** [comment]
> Yes. usr/lib/lv2 is for Plugins comming from your distribution, .lv2 is for presets and for Plugins comming from elswere.

interesting, I always thought it was just a quirk of linux
