### ISSUE TITLE
Adaptation of Your Plugin for GUI Support in mod-desktop LV2 Host on Linux

### ISSUE THREAD

**Issue by Riebeck-one** [brummer10/Ratatouille.lv2#9]
Hi,
I'm sorry, but I didn't know where else to contact you.
I wanted to share that I adapted your plugin to have a GUI when used with the mod-desktop LV2 host on Linux.

Here is the repository: [https://github.com/Riebeck-one/ratatouille-modgui/tree/main](https://github.com/Riebeck-one/ratatouille-modgui/tree/main)

If there are any issues with it, please let me know.

**Comment by brummer10** [comment]
Hi
This is cool. 
Only, the "choose a NAM model" may be a bit misleading, maybe you could call it "choose a NAM/AIDA-X model" to make clear that both formats been sported.

**Comment by Riebeck-one** [comment]
You're right, I just updated it.

**Comment by brummer10** [comment]
Nice. I've added a hint to your MOD GUI on the README.
Nice times for linux users.
